### ISSUE TITLE
Files being loaded from the wrong location

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1080]
It seems openflights.js and openflights.css are being loaded from `/var/www/` rather than `/var/www/openflights`

```
[Thu Mar 24 22:50:16.279798 2022] [:error] [pid 9056] [client 10.13.37.22:53167] PHP Fatal error:  Uncaught exception 'Exception' with message '/var/www/openflights.css does not exist; can't get URL with date.' in /var/www/openflights/php/helper.php:170\nStack trace:\n#0 /var/www/openflights/index.php(29): fileUrlWithDate('/openflights.cs...')\n#1 {main}\n  thrown in /var/www/openflights/php/helper.php on line 170, referer: http://10.13.37.36/

[Thu Mar 24 22:54:42.071336 2022] [:error] [pid 9055] [client 10.13.37.22:55952] PHP Fatal error:  Uncaught exception 'Exception' with message '/var/www/openflights.js does not exist; can't get URL with date.' in /var/www/openflights/php/helper.php:170\nStack trace:\n#0 /var/www/openflights/index.php(41): fileUrlWithDate('/openflights.js')\n#1 {main}\n  thrown in /var/www/openflights/php/helper.php on line 170, referer: http://10.13.37.36/
```

**Comment by chrisrosset** [comment]
@reedy I think this was related to the server migration. Good to close?
