### ISSUE TITLE
attempting to edit an airport yields an internal server error

### ISSUE THREAD

**Issue by mlc** [jpatokal/openflights#1314]
hi, thanks for this great project!

I noticed that VQS airport is in the wrong place on OpenFlights ([wikipedia has the right coordinates](https://en.wikipedia.org/wiki/Antonio_Rivera_Rodr%C3%ADguez_Airport) on the north side of the island) and so tried to submit an update using the form on the site.

However, when I pressed the "save changes" button, I got text reading "internal server error" on my screen. No further information was available in the network trace that I could find, and no issue for the edit was posted here, as far as I can tell.

Thanks for having a look!

**Comment by reedy** [comment]
Guess we should test this in dev... But don't have acces to the server logs...

**Comment by reedy** [comment]
Seems to work fine in my dev environtment...

Can you upload a screenshot of what you were trying to save?

Thanks

**Comment by dicorynia** [comment]
Trying to edit CDG2 Digby, wrongly located in France instead of Canada (coords are fine though), I also get "Internal Server Error":
![image](https://github.com/jpatokal/openflights/assets/31208891/3f52e1de-e6bd-48c9-927e-b0c9bb553bc5)

**Comment by reedy** [comment]
I guess you changing the name as well?

I can't save it if I just change the country due to https://github.com/jpatokal/openflights/issues/1351

If I change it to remove the `()` in my dev install, I can save to the database...

Let me now try if not an admin

**Comment by reedy** [comment]
Without GitHub setup, I seem to get that error...

```
2023/07/15 14:49:11 [error] 938#938: *696 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Github\Exception\RuntimeException: Bad credentials in /var/www/openflights/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:138
Stack trace:
#0 /var/www/openflights/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(31): Github\HttpClient\Plugin\GithubExceptionThrower->Github\HttpClient\Plugin\{closure}()
#1 /var/www/openflights/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php(28): Http\Client\Promise\HttpFulfilledPromise->then()
#2 /var/www/openflights/vendor/php-http/client-common/src/PluginChain.php(44): Github\HttpClient\Plugin\GithubExceptionThrower->handleRequest()
#3 /var/www/openflights/vendor/php-http/client-common/src/PluginChain.php(59): Http\Client\Common\PluginChain->Http\Client\Common\{closure}()
#4 /var/www/openflights/vendor/php-http/client-common/src/PluginClient.php(87): Http\Client\Common\PluginChain->__invoke()
#5 /var/www/openflights/vendor/php-http/client-common"
```

Seems a good time to resolve https://github.com/jpatokal/openflights/blob/83ab24a/php/apsearch.php#L181

**Comment by reedy** [comment]
I probably broke this in https://github.com/jpatokal/openflights/commit/c03f72006444dfc2485eec28ba936d3d74d1631d...

Tested working now, as seen at https://github.com/reedy/openflights/issues/1

@jpatokal this will need deploying at some point... Code is obviously undergoing quite a bit of change atm.

Also, worth checking the token you're using has not expired...

And whether we want to do #1171 at the same time...


Then see if the submission is still broken on the live site

**Comment by dicorynia** [comment]
> I guess you changing the name as well?
> 
> I can't save it if I just change the country due to #1351
> 
> If I change it to remove the `()` in my dev install, I can save to the database...
> 
> Let me now try if not an admin

Yes I tried without the `()` after getting the message about special characters; then I got what I screenshot.

**Comment by jpatokal** [comment]
FWIW, I checked the token on Github and it's a "classic" token that has no expiration date, so not quite sure what the issue is.

**Comment by reedy** [comment]
I'll test it later on the live site...

**Comment by reedy** [comment]
Yeah.. Still doesn't work. I see it pop up trying to save, but then no error or succeed message...

**Comment by wafliron** [comment]
Same when adding as new - no more error, and it actually does show a message suggesting it was successful, but there's no sign after that of the newly-added airport via search.

**Comment by reedy** [comment]
I'll have more of a play with my developer setup again and confirm that that is still all working (now that updated code is deployed).

It should be creating GitHub issues or leaving comments on existing ones, not actually creating or editing airports for most users

**Comment by wafliron** [comment]
My bad, I didn't realise it wasn't a direct edit / add.

That said, I don't see any sign of an issue / comment re the airport I just tried to edit, and then tried add as new (after edit appeared to fail) - Ol Kiombo Airstrip (OLX / HKOK). So maybe the functionality to create an issue / comment isn't working.

Although I do see a four year old report (https://github.com/jpatokal/openflights/issues/990) for the same airport with what appears to be correct data (there's three entries for it on OpenFlights now, all of which are either incorrect or incomplete). Just mentioning in case some sort of dupe-report detection blocked an issue / comment being added when I just tried to edit / add.

**Comment by reedy** [comment]
It should leave a comment on existing tasks, as per https://github.com/reedy/openflights/issues/1 and https://github.com/reedy/openflights/issues/2

**Comment by wafliron** [comment]
Yep, no sign of an issue or comment being created for either my edit or add. See https://github.com/jpatokal/openflights/issues?q=olx - only references to the airport code I used is this issue, and the four-year-old issue I mentioned above.

**Comment by reedy** [comment]
"Unfortunately", it works fine on my dev install

![Screenshot 2023-10-19 at 13 12 44](https://github.com/jpatokal/openflights/assets/67615/49a4b1d8-f35d-4d1b-bc1c-0f72ec4922a0)

![Screenshot 2023-10-19 at 13 14 10](https://github.com/jpatokal/openflights/assets/67615/5faf8074-c50d-4b9e-b2cf-42e4dd67b60d)

https://github.com/reedy/openflights/issues/3

I then closed the issue...

![Screenshot 2023-10-19 at 13 14 46](https://github.com/jpatokal/openflights/assets/67615/d118255d-12ba-4086-8f12-92515ac20475)

https://github.com/reedy/openflights/issues/4

So definitely feels to be something local to "production"

**Comment by reedy** [comment]
@jpatokal Are you seeing any fatal/exceptions in the logs?
